# Régression linéaire à plusieurs variables - Exercices tirés du MOOC d'Andrew Ng

## Chargement des données

Le jeu de données donne la valeur de plusieurs maisons, ainsi que leur taille (pieds carrés) et le nombre de chambres à coucher

### Chargez les données du fichier ex1data1.csv

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("data.csv")

### Visualisez les données (valeurs réelles)

Maintenant, nous avons deux 'features'. Voyez si elles ont le même ordre de grandeur

In [3]:
data
print (data)

    size  nb_bedrooms   price
0   2104            3  399900
1   1600            3  329900
2   2400            3  369000
3   1416            2  232000
4   3000            4  539900
5   1985            4  299900
6   1534            3  314900
7   1427            3  198999
8   1380            3  212000
9   1494            3  242500
10  1940            4  239999
11  2000            3  347000
12  1890            3  329999
13  4478            5  699900
14  1268            3  259900
15  2300            4  449900
16  1320            2  299900
17  1236            3  199900
18  2609            4  499998
19  3031            4  599000
20  1767            3  252900
21  1888            2  255000
22  1604            3  242900
23  1962            4  259900
24  3890            3  573900
25  1100            3  249900
26  1458            3  464500
27  2526            3  469000
28  2200            3  475000
29  2637            3  299900
30  1839            2  349900
31  1000            1  169900
32  2040  

## Définissez quelques variables utiles

### Définissez X et y

X est maintenant une matrice de dimensions m x 2

In [4]:
X = np.array(data)
y = np.array([data.price])
X = X[ :, :2]
print (X, y)

[[2104    3]
 [1600    3]
 [2400    3]
 [1416    2]
 [3000    4]
 [1985    4]
 [1534    3]
 [1427    3]
 [1380    3]
 [1494    3]
 [1940    4]
 [2000    3]
 [1890    3]
 [4478    5]
 [1268    3]
 [2300    4]
 [1320    2]
 [1236    3]
 [2609    4]
 [3031    4]
 [1767    3]
 [1888    2]
 [1604    3]
 [1962    4]
 [3890    3]
 [1100    3]
 [1458    3]
 [2526    3]
 [2200    3]
 [2637    3]
 [1839    2]
 [1000    1]
 [2040    4]
 [3137    3]
 [1811    4]
 [1437    3]
 [1239    3]
 [2132    4]
 [4215    4]
 [2162    4]
 [1664    2]
 [2238    3]
 [2567    4]
 [1200    3]
 [ 852    2]
 [1852    4]
 [1203    3]] [[399900 329900 369000 232000 539900 299900 314900 198999 212000 242500
  239999 347000 329999 699900 259900 449900 299900 199900 499998 599000
  252900 255000 242900 259900 573900 249900 464500 469000 475000 299900
  349900 169900 314900 579900 285900 249900 229900 345000 549000 287000
  368500 329900 314000 299000 179900 299900 239500]]


### Initialisez theta (combien de dimensions?)

In [5]:
theta = np.zeros(3)

### Vérifiez les dimensions de theta et de X. Sont-elles compatibles pour implémenter la fonction d'hypothèse sous forme vectorisée?

In [6]:
print (theta.ndim, X.ndim)

1 2


### Modifiez X en conséquence

In [7]:
X = np.insert(X, 0, 0, axis=1)
print(X)

[[   0 2104    3]
 [   0 1600    3]
 [   0 2400    3]
 [   0 1416    2]
 [   0 3000    4]
 [   0 1985    4]
 [   0 1534    3]
 [   0 1427    3]
 [   0 1380    3]
 [   0 1494    3]
 [   0 1940    4]
 [   0 2000    3]
 [   0 1890    3]
 [   0 4478    5]
 [   0 1268    3]
 [   0 2300    4]
 [   0 1320    2]
 [   0 1236    3]
 [   0 2609    4]
 [   0 3031    4]
 [   0 1767    3]
 [   0 1888    2]
 [   0 1604    3]
 [   0 1962    4]
 [   0 3890    3]
 [   0 1100    3]
 [   0 1458    3]
 [   0 2526    3]
 [   0 2200    3]
 [   0 2637    3]
 [   0 1839    2]
 [   0 1000    1]
 [   0 2040    4]
 [   0 3137    3]
 [   0 1811    4]
 [   0 1437    3]
 [   0 1239    3]
 [   0 2132    4]
 [   0 4215    4]
 [   0 2162    4]
 [   0 1664    2]
 [   0 2238    3]
 [   0 2567    4]
 [   0 1200    3]
 [   0  852    2]
 [   0 1852    4]
 [   0 1203    3]]


## Écrivez une fonction pour centrer et réduire les features

In [8]:
print(X)
def featureScaleNormalize(X):
    mean = X.mean(0)
    stdev = X.std(0)
    stdev[0] = 1
    m = len(X)
    X = X.astype(float)
    for x in range(m):
        X[x] -= mean
        X[x] /= stdev
    return X, mean, stdev
X, mean, stdev = featureScaleNormalize(X)
print (X, mean, stdev)

[[   0 2104    3]
 [   0 1600    3]
 [   0 2400    3]
 [   0 1416    2]
 [   0 3000    4]
 [   0 1985    4]
 [   0 1534    3]
 [   0 1427    3]
 [   0 1380    3]
 [   0 1494    3]
 [   0 1940    4]
 [   0 2000    3]
 [   0 1890    3]
 [   0 4478    5]
 [   0 1268    3]
 [   0 2300    4]
 [   0 1320    2]
 [   0 1236    3]
 [   0 2609    4]
 [   0 3031    4]
 [   0 1767    3]
 [   0 1888    2]
 [   0 1604    3]
 [   0 1962    4]
 [   0 3890    3]
 [   0 1100    3]
 [   0 1458    3]
 [   0 2526    3]
 [   0 2200    3]
 [   0 2637    3]
 [   0 1839    2]
 [   0 1000    1]
 [   0 2040    4]
 [   0 3137    3]
 [   0 1811    4]
 [   0 1437    3]
 [   0 1239    3]
 [   0 2132    4]
 [   0 4215    4]
 [   0 2162    4]
 [   0 1664    2]
 [   0 2238    3]
 [   0 2567    4]
 [   0 1200    3]
 [   0  852    2]
 [   0 1852    4]
 [   0 1203    3]]
[[ 0.00000000e+00  1.31415422e-01 -2.26093368e-01]
 [ 0.00000000e+00 -5.09640698e-01 -2.26093368e-01]
 [ 0.00000000e+00  5.07908699e-01 -2.26093368e-01]


### Maintenant nous allons devoir adapter nos fonctions _predict_, _fit_, et _cost_ à une situation à plusieurs variables

In [9]:
def predict(X, theta):
    
    

SyntaxError: unexpected EOF while parsing (<ipython-input-9-f6161b21dc24>, line 2)

In [ ]:
def cost(X, y, theta):
    

In [ ]:
def fit_with_cost(X, y, theta, alpha, num_iters):
    
    
    
    
    return theta, J_history

## Lancez l'entrainement du modèle

Vous êtes libres de choisir alpha et num_iters cette fois!

## Visualisez l'évolution du coût (graphe de convergence)

In [ ]:
fit = plt.figure()
ax = plt.axes()
ax.plot(J_history)

## Testez votre modèle

Que vaut une maison de 1650 pieds carrés et de 3 chambres à coucher? (Si la valeur est aberrante, vous avez peut-être oublié une étape...)

### Réécrivez votre fonction fit pour qu'elle prenne en compte un parametre de regularisation (L1, L2 pour Lasso ou Ridge) et adapte la mise  a jour de theta an fonction de la regularization précisée

In [ ]:
def fit_with_regularization(X, y, theta, alpha, num_iters, regularization=""):
    
    
    
    
    return theta, J_history

### La fonction fit au complet. Ajoutez un dernier parametre qui précise le gradient employé (stochastic, mini_batch(avec le batch_size), batch). Pour la descente de gradient stochastic et minibatch on met a jour le learning rate avec la formule du learning rate decay

In [ ]:
def complete_fit(X, y, theta, alpha, num_iters, regularization="", gradient_descent="batch", batch_size=4, decay_rate=1):
    
    
    
    
    return theta, J_history